# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 14
    rounding_power = 3

    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(0,0,0,0.5)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 2
        passes = 3

        vibrancy = 0.1696
    }
}
