#    ____                                            
#   / __ \_________  ____ __________ _____ ___  _____
#  / /_/ / ___/ __ \/ __ `/ ___/ __ `/ __ `__ \/ ___/
# / ____/ /  / /_/ / /_/ / /  / /_/ / / / / / (__  ) 
#/_/   /_/   \____/\__, /_/   \__,_/_/ /_/ /_/____/  
#                 /____/                             

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = awww-daemon
exec-once = qs -c pill
exec-once = hypridle
