windowrule = float true, size 1000 500, match:class waypaper
windowrule = float true, size 820 380, move 57 663, match:class kitty, match:title rmpc
windowrule = decorate false, match:class firefox
#windowrule {
 # name = move-kitty
  #match:class = kitty
 # match:title = rmpc
 # move = 30 82
 # animation = slide
#}

# windowrule = float, class:^(kitty)$, title:^(rmpc.*)$
# windowrule = size 1000 500, class:^(kitty)$, title:^(rmpc.*)$
# windowrule = center, class:^(kitty)$, title:^(rmpc.*)$



# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}

windowrule {
  name = apply-something
  match:class = my-window

  border_size = 10
}

xwayland{
  force_zero_scaling = true
}
