source = $HOME/.config/hypr/everforest.conf
source = ~/.cache/wal/colors-kitty.conf

$font = JetBrainsMono Nerd Font

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  path = /home/melovink/nordic-wallpapers/wallpapers/nordic-obsession.png
  blur_passes = 0
  blur_size = 0
}

# image {
#   monitor = 
#   size = 100
#   rounding = 100
#   border_size = 3
#   border_color = $Statusline1
#   rotate = 5
#   path = /home/melovink/.config/hypr/goofy.jpeg
#   position = 0, 30
#   # halign = center
#   # valign = center
# }

#time
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H")"
  font_size = 120
  color = $Statusline1
  font_family = JetBrains Mono Extrabold
  position = 0, 190
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%M")"
  font_size = 120
  color = $Statusline1
  font_family = JetBrains Mono Extrabold
  position = 0, 40
  halign = center
  valign = center
}

#date
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  font_size = 15
  color = $Statusline1
  font_family = JetBrains Mono
  position = 0, -70
  halign = center
  valign = center
}

# LAYOUT
label {
 monitor =
 text = Layout: $LAYOUT
 color = $Statusline1
 font_size = 10
 font_family = JetBrains Mono
 position = 30, -30
 halign = left
 valign = top
}

#mpd
# image{
#   monitor = 
#   size = 100
#   rounding = 100
#   border_size = 3
#   border_color = $Statusline1
#   rotate = 5
#   path = exec mpc readpicture 
#   position = -600, 30
# }
label {
  monitor = 
  text =  cmd[update:2000] echo "♪ Now Playing :"
  color = $Statusline1
  font_size = 10
  position = 30, -60
  halign = left
  valign = top

}
label {
  monitor = 
  text =  cmd[update:2000] mpc current 
  color = $Statusline1
  position = 130, -60
  font_size = 10
  halign = left
  valign = top

}

# INPUT FIELD
input-field {
  monitor =
  size = 200, 50
  outline_thickness = 2
  dots_size = 0.23
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgb(129, 161, 193)
  font_color = rgb(129, 161, 193)
  inner_color = rgba(0,0,0,0.4)
  fade_on_empty = false
  placeholder_text = $USER is on a break
  hide_input = false
  check_color = rgb(129, 161, 193)
  fail_color = $Red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $Purple
  position = 0, -280
  halign = center
  valign = center
}
