music_directory "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file "~/.config/mpd/database"
state_file "~/.config/mpd/state"
sticker_file "~/.config/mpd/sticker.sql"

audio_output {
        type            "alsa"
        name            "High Fidelity"
        # device          "hw:2,0"
        auto_resample   "no"
        mixer_type      "none"
}
#
# audio_output {
#     type "fifo"
#     name "my_fifo"
#     path "/tmp/mpd.fifo"
#     format "96000:24:2"
# }
#
# audio_output {
#     type "pipewire"
#     name "pipewire output"
# }

audio_buffer_size "8192"
buffer_before_play "25%"
